version: "2"

services:
  namenode:
    build: ./hadoop-namenode
    container_name: namenode
    hostname: namenode
    networks:
      - hadoop
    ports:
      - "8020:8020"
      - "50070:50070"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  resourcemanager:
    build: ./hadoop-resourcemanager
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
      - datanode1
      - datanode2
    networks:
      - hadoop
    links:
      - namenode
    ports:
      - "8030:8030"
      - "8031:8031"
      - "8032:8032"
      - "8088:8088"
    env_file:
      - ./hadoop.env

  historyserver:
    build: ./hadoop-historyserver
    container_name: historyserver
    hostname: historyserver
    volumes:
      - ./data/historyserver:/hadoop/yarn/timeline
    depends_on:
      - namenode
      - datanode1
      - datanode2      
    networks:
      - hadoop
    links:
      - namenode
    ports:
      - "8188:8188"
    env_file:
      - ./hadoop.env

  nodemanager:
    build: ./hadoop-nodemanager
    container_name: nodemanager
    hostname: nodemanager
    depends_on:
      - namenode
      - resourcemanager
    networks:
      - hadoop
    links:
      - namenode
      - resourcemanager
    ports:
      - "8042:8042"
    env_file:
      - ./hadoop.env

  datanode1:
    build: ./hadoop-datanode
    container_name: datanode1
    hostname: datanode1
    depends_on:
      - namenode
    networks:
      - hadoop
    ports:
      - "50075:50075"
      - "50010:50010"
      - "50020:50020"
    links:
      - namenode
    volumes:
      - ./data/datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    build: ./hadoop-datanode
    container_name: datanode2
    hostname: datanode2
    depends_on:
      - namenode
    networks:
      - hadoop
        #ports:
        #- "50075:50075"
        #- "50010:50010"
        #- "50020:50020"
    links:
      - namenode
    volumes:
      - ./data/datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode3:
    build: ./hadoop-datanode
    container_name: datanode3
    hostname: datanode3
    depends_on:
      - namenode
    networks:
      - hadoop
        #ports:
        #- "50075:50075"
        #- "50010:50010"
        #- "50020:50020"
    links:
      - namenode
    volumes:
      - ./data/datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

networks:
  hadoop:
    external:
      name: hadoop
